version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:9090

  server:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - hardhat
    environment:
      - MONGO_URI=mongodb://mongo:27017/flowfund
      - ETHEREUM_RPC_URL=http://hardhat:8545

  hardhat:
    build:
      context: ./hardhat
      dockerfile: Dockerfile
    ports:
      - "8545:8545"


