/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/TransactionHistoryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/components/GradientBackground`; params?: Router.UnknownInputParams; } | { pathname: `/components/Login`; params?: Router.UnknownInputParams; } | { pathname: `/components/MarketPlace`; params?: Router.UnknownInputParams; } | { pathname: `/components/UserStats`; params?: Router.UnknownInputParams; } | { pathname: `/components/Wallet`; params?: Router.UnknownInputParams; } | { pathname: `/config/api`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/UserStatsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/TransactionHistoryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/CreateAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/components/GradientBackground`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/components/MarketPlace`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UserStats`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/config/api`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/UserStatsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/TransactionHistoryScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/CreateAccount${`?${string}` | `#${string}` | ''}` | `/components/GradientBackground${`?${string}` | `#${string}` | ''}` | `/components/Login${`?${string}` | `#${string}` | ''}` | `/components/MarketPlace${`?${string}` | `#${string}` | ''}` | `/components/UserStats${`?${string}` | `#${string}` | ''}` | `/components/Wallet${`?${string}` | `#${string}` | ''}` | `/config/api${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/tabs/UserStatsScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/TransactionHistoryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `/components/GradientBackground`; params?: Router.UnknownInputParams; } | { pathname: `/components/Login`; params?: Router.UnknownInputParams; } | { pathname: `/components/MarketPlace`; params?: Router.UnknownInputParams; } | { pathname: `/components/UserStats`; params?: Router.UnknownInputParams; } | { pathname: `/components/Wallet`; params?: Router.UnknownInputParams; } | { pathname: `/config/api`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/UserStatsScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
